site_name: Home Cloud Server
repo_url: https://github.com/NinePiece2/HomeCloudServer
repo_name: NinePiece2/HomeCloudServer
site_url: https://homecloudserver.romitsagu.com
copyright: Copyright © 2025 Romit Sagu

theme:
  language: en
  font:
    text: Poppins
    code: Fira Code
  icon:
      repo: fontawesome/brands/github
  name: 'material'
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - toggle.dark_mode
    - content.code.copy
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://GitHub.com/NinePiece2
    - icon: fontawesome/brands/linkedin
      link: https://Linkedin.com/in/romit-sagu

docs_dir: docs
nav:
  - 'Overview': 'README.md'
  - 'Old Versions':
      - 'v1.0': 'Old_Versions/v1.0/README.md'